apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-hpsearch
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-hpsearch
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.worker }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-hpsearch
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.worker }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: {{ .Values.hpsearch.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-hpsearch
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-hpsearch
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.worker }}
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-hpsearch
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}-hpsearch
        image: "{{ .Values.hpsearch.image }}:{{ .Values.hpsearch.imageTag }}"
        imagePullPolicy: {{ .Values.hpsearch.imagePullPolicy }}
        args: ["--concurrency={{ .Values.hpsearch.concurrency }}"]
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
{{ include "config.persistence.data" . | indent 8 }}
{{ include "config.persistence.outputs" . | indent 8 }}
{{ include "config.persistence.logs" . | indent 8 }}
{{ include "config.celery.hpsearch" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.hpsearch.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.hpsearch.resources.limits | indent 12 }}
          {{- end }}
