apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-monitors
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-monitors
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.log }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-monitors
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.log }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-monitors
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-monitors
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.log }}
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-monitors
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
      containers:
      {{- if .Values.eventMonitors.namespace.enabled }}
      # namespace event monitor
      - name: {{ .Chart.Name }}-namespace
        image: "{{ .Values.eventMonitors.namespace.image }}:{{ .Values.eventMonitors.namespace.imageTag }}"
        imagePullPolicy: {{ .Values.eventMonitors.namespace.imagePullPolicy }}
        args: ["--sleep_interval={{ .Values.eventMonitors.namespace.sleepInterval }}", "--persist={{ .Values.eventMonitors.namespace.persists }}"]
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.eventMonitors.namespace.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.eventMonitors.namespace.resources.limits | indent 12 }}
          {{- end }}
      {{- end }}
      # statuses event monitor
      {{- if .Values.eventMonitors.statuses.enabled }}
      - name: {{ .Chart.Name }}-statuses
        image: "{{ .Values.eventMonitors.statuses.image }}:{{ .Values.eventMonitors.statuses.imageTag }}"
        imagePullPolicy: {{ .Values.eventMonitors.statuses.imagePullPolicy }}
        args: ["--sleep_interval={{ .Values.eventMonitors.statuses.sleepInterval }}", "--persist={{ .Values.eventMonitors.statuses.persists }}"]
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.eventMonitors.statuses.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.eventMonitors.statuses.resources.limits | indent 12 }}
          {{- end }}
      {{- end }}
