{{- if .Values.resourcesDaemon.enabled -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "polyaxon.fullname" . }}-resources
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-resources
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.log }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-resources
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.log }}
    app.kubernetes.io/managed-by: "helm"
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-resources
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.log }}
    spec:
      {{- if .Values.resourcesDaemon.tolerations }}
      tolerations:
{{ toYaml .Values.resourcesDaemon.tolerations | indent 8 }}
      {{- end }}
{{ include "config.sa" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}-resources
        image: "{{ .Values.resourcesDaemon.image }}:{{ .Values.resourcesDaemon.imageTag }}"
        imagePullPolicy: {{ .Values.resourcesDaemon.imagePullPolicy }}
        args: ["--sleep_interval={{ .Values.resourcesDaemon.sleepInterval }}", "--persist={{ .Values.resourcesDaemon.persists }}"]
#        securityContext:
#          privileged: true
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        env:
{{ include "config.envs" . | indent 8 }}
        resources:
          requests:
{{ toYaml .Values.resourcesDaemon.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.resourcesDaemon.resources.limits | indent 12 }}
          {{- end }}
        volumeMounts:
{{ include "volumes.dirMounts" . | indent 8}}
      volumes:
{{ include "volumes.dirs" . | indent 6 }}
{{- end }}
