apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "polyaxon.fullname" . }}-scheduler
  annotations:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
  labels:
    app: {{ template "polyaxon.fullname" . }}-scheduler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    type: {{ .Values.types.core }}
    role: {{ .Values.roles.worker }}
    app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-resources
    app.kubernetes.io/instance: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: "{{ .Chart.Version }}"
    app.kubernetes.io/part-of: {{ .Values.types.core }}
    app.kubernetes.io/component: {{ .Values.roles.worker }}
    app.kubernetes.io/managed-by: "helm"
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-scheduler
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app: {{ template "polyaxon.fullname" . }}-scheduler
        release: "{{ .Release.Name }}"
        type: {{ .Values.types.core }}
        role: {{ .Values.roles.worker }}
        app.kubernetes.io/name: {{ template "polyaxon.fullname" . }}-scheduler
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
{{ include "securityContext" . | indent 6 }}
{{ include "config.scheduling" . | indent 6 }}
{{ include "config.sa" . | indent 6 }}
      containers:
      - name: {{ .Chart.Name }}-scheduler
        image: "{{ .Values.scheduler.image }}:{{ .Values.scheduler.imageTag }}"
        imagePullPolicy: {{ .Values.scheduler.imagePullPolicy }}
        args: ["--concurrency={{ .Values.scheduler.concurrency }}"]
        envFrom:
{{ include "config.envFrom" . | indent 8 }}
        env:
{{ include "config.dns" . | indent 8 }}
{{ include "config.envs" . | indent 8 }}
{{ include "config.persistence.outputs" . | indent 8 }}
{{ include "config.persistence.data" . | indent 8 }}
{{ include "config.persistence.logs" . | indent 8 }}
{{ include "config.persistence.upload" . | indent 8 }}
{{ include "config.persistence.repos" . | indent 8 }}
{{ include "config.storesSecrets.outputs" . | indent 8 }}
{{ include "config.storesSecrets.logs" . | indent 8 }}
{{ include "config.celery.scheduler" . | indent 8 }}
        volumeMounts:
{{ include "volumes.dirMounts" . | indent 8}}
{{ include "volumes.volumeMounts.logs" . | indent 8}}
{{ include "volumes.volumeMounts.outputs" . | indent 8}}
        resources:
          requests:
{{ toYaml .Values.scheduler.resources.requests | indent 12 }}
          {{- if .Values.limitResources }}
          limits:
{{ toYaml .Values.scheduler.resources.limits | indent 12 }}
          {{- end }}
      volumes:
{{ include "volumes.dirs" . | indent 6 }}
{{ include "volumes.volumes.logs" . | indent 6 }}
{{ include "volumes.volumes.outputs" . | indent 6}}
